#ifndef __toolbox_msgs__msg__MultiContactCoMRegionPreviewMessage__idl__
#define __toolbox_msgs__msg__MultiContactCoMRegionPreviewMessage__idl__

#include "toolbox_msgs/msg/./MultiContactCoMRegionMessage_.idl"
module toolbox_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the multi-contact feasibility module
       * This message acts as an output of the module and contains a set of preview CoM regions if contacts are removed.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::MultiContactCoMRegionPreviewMessage_")
      struct MultiContactCoMRegionPreviewMessage
      {
        sequence<toolbox_msgs::msg::dds::MultiContactCoMRegionMessage, 15> com_preview_regions;
      };
    };
  };
};

#endif
